// The code generated by capnp schema compilation assumes that the "test_all_types_capnp" module is at the crate root
pub mod test_all_types_capnp {
    include!(concat!(env!("OUT_DIR"), "/test_all_types_capnp.rs"));
}